[Icon Theme]
Name=Adwaita-cinnamon
Comment=Icon theme extension for Cinnamon 
Inherits=Adwaita
Example=folder

Directories=scalable/actions,scalable/apps,scalable/categories,scalable/devices,scalable/emblems,scalable/places

[scalable/actions]
Context=Actions
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[scalable/categories]
Context=Categories
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[scalable/emblems]
Context=Emblems
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=96
MinSize=8
MaxSize=512
Type=Scalable
